# Generated by Django 3.1.7 on 2021-06-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktualnosci', '0003_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='eng_subtitle',
            field=models.CharField(default='aaa', max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='eng_text',
            field=models.TextField(default='aaa'),
        ),
        migrations.AddField(
            model_name='news',
            name='eng_title',
            field=models.CharField(default='aaa', max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle',
            field=models.CharField(default='aaa', max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
