# Generated by Django 3.1.7 on 2021-06-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktualnosci', '0004_auto_20210605_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='eng_subtitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='eng_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='eng_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='subtitle',
            field=models.CharField(max_length=200),
        ),
    ]
