# Generated by Django 3.1.7 on 2021-06-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktualnosci', '0005_auto_20210605_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wniosek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('nip', models.IntegerField(max_length=10)),
                ('regon', models.IntegerField(max_length=14)),
                ('krs', models.IntegerField(blank=True, max_length=10)),
                ('adres', models.CharField(max_length=50)),
                ('branza', models.CharField(max_length=30)),
                ('forma_prawna', models.CharField(max_length=50)),
                ('normy', models.CharField(max_length=100)),
                ('zakres_dzialalnosci', models.CharField(max_length=100)),
                ('liczba_zatrudnionych', models.IntegerField(max_length=9)),
                ('liczba_zatrudnionych_system', models.IntegerField(max_length=9)),
                ('miejsce', models.CharField(max_length=50)),
                ('przedstawiciel', models.CharField(max_length=200)),
                ('zrodlo', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
