# Generated by Django 3.1.7 on 2021-06-06 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktualnosci', '0006_auto_20210606_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wniosek',
            name='krs',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='wniosek',
            name='liczba_zatrudnionych',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='wniosek',
            name='liczba_zatrudnionych_system',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='wniosek',
            name='nip',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='wniosek',
            name='regon',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
