# Generated by Django 3.1.7 on 2021-06-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktualnosci', '0008_auto_20210606_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wniosek',
            name='zrodlo',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
