# Generated by Django 3.1.7 on 2021-06-06 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktualnosci', '0009_auto_20210606_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wniosek',
            name='krs',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
