# Generated by Django 3.1.7 on 2021-06-08 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktualnosci', '0010_auto_20210606_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapytanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=50)),
                ('tel', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('nip', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('internet', models.CharField(max_length=30)),
                ('prezes', models.CharField(max_length=30)),
                ('krs', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('przedmiot_dzialalnosci', models.CharField(max_length=30)),
                ('fax', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('email', models.CharField(max_length=50)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('stanowisko', models.CharField(max_length=50)),
                ('telefon', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('email2', models.CharField(max_length=50)),
                ('norma', models.CharField(max_length=50)),
                ('certyfikat', models.CharField(max_length=50)),
                ('liczba_zatrudnionych', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('liczba_zatrudnionych_system', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('zakres', models.CharField(max_length=200)),
            ],
        ),
    ]
